// To parse this JSON data, do
//
//     final warehouseDetails = warehouseDetailsFromJson(jsonString);

class Warehouse {
  // int companyId;
  // String? logo;
  // String? darkLogo;
  // String name;
  // String slug;
  // String email;
  // String phone;
  // int showEmailOnInvoice;
  // int showPhoneOnInvoice;
  // dynamic address;
  // String termsCondition;
  // dynamic bankDetails;
  // dynamic signature;
  // dynamic gstInNo;
  // String? qrCode;
  // String? upiId;
  // int onlineStoreEnabled;
  // String customersVisibility;
  // String suppliersVisibility;
  // String productsVisibility;
  // String defaultPosOrderStatus;
  // int showMrpOnInvoice;
  // int showDiscountTaxOnInvoice;
  // DateTime createdAt;
  // DateTime updatedAt;
  // String posType;
  // String setPosType;
  // String isBarcode;
  // String isWainvoice;
  // String firstInvoiceNo;
  // String prefixInvoice;
  // String invoiceSpliter;
  // String? suffixInvoice;
  // String? resetInvoice;
  // String invoiceStarted;
  // String dailyReset;
  // dynamic otp;
  // String xid;
  // String logoUrl;
  // String darkLogoUrl;
  // dynamic signatureUrl;
  //
  // Warehouse({
  //   required this.companyId,
  //   required this.logo,
  //   required this.darkLogo,
  //   required this.name,
  //   required this.slug,
  //   required this.email,
  //   required this.phone,
  //   required this.showEmailOnInvoice,
  //   required this.showPhoneOnInvoice,
  //   required this.address,
  //   required this.termsCondition,
  //   required this.bankDetails,
  //   required this.signature,
  //   required this.gstInNo,
  //   required this.qrCode,
  //   required this.upiId,
  //   required this.onlineStoreEnabled,
  //   required this.customersVisibility,
  //   required this.suppliersVisibility,
  //   required this.productsVisibility,
  //   required this.defaultPosOrderStatus,
  //   required this.showMrpOnInvoice,
  //   required this.showDiscountTaxOnInvoice,
  //   required this.createdAt,
  //   required this.updatedAt,
  //   required this.posType,
  //   required this.setPosType,
  //   required this.isBarcode,
  //   required this.isWainvoice,
  //   required this.firstInvoiceNo,
  //   required this.prefixInvoice,
  //   required this.invoiceSpliter,
  //   required this.suffixInvoice,
  //   required this.resetInvoice,
  //   required this.invoiceStarted,
  //   required this.dailyReset,
  //   required this.otp,
  //   required this.xid,
  //   required this.logoUrl,
  //   required this.darkLogoUrl,
  //   required this.signatureUrl,
  // });
  //
  // factory Warehouse.fromJson(Map<String, dynamic> json) => Warehouse(
  //       companyId: json["company_id"],
  //       logo: json["logo"],
  //       darkLogo: json["dark_logo"],
  //       name: json["name"],
  //       slug: json["slug"],
  //       email: json["email"],
  //       phone: json["phone"],
  //       showEmailOnInvoice: json["show_email_on_invoice"],
  //       showPhoneOnInvoice: json["show_phone_on_invoice"],
  //       address: json["address"],
  //       termsCondition: json["terms_condition"],
  //       bankDetails: json["bank_details"],
  //       signature: json["signature"],
  //       gstInNo: json["gst_in_no"],
  //       qrCode: json["qr_code"],
  //       upiId: json["upi_id"],
  //       onlineStoreEnabled: json["online_store_enabled"],
  //       customersVisibility: json["customers_visibility"],
  //       suppliersVisibility: json["suppliers_visibility"],
  //       productsVisibility: json["products_visibility"],
  //       defaultPosOrderStatus: json["default_pos_order_status"],
  //       showMrpOnInvoice: json["show_mrp_on_invoice"],
  //       showDiscountTaxOnInvoice: json["show_discount_tax_on_invoice"],
  //       createdAt: DateTime.parse(json["created_at"]),
  //       updatedAt: DateTime.parse(json["updated_at"]),
  //       posType: json["pos_type"],
  //       setPosType: json["set_pos_type"],
  //       isBarcode: json["is_barcode"],
  //       isWainvoice: json["is_wainvoice"],
  //       firstInvoiceNo: json["first_invoice_no"],
  //       prefixInvoice: json["prefix_invoice"],
  //       invoiceSpliter: json["invoice_spliter"],
  //       suffixInvoice: json["suffix_invoice"],
  //       resetInvoice: json["reset_invoice"],
  //       invoiceStarted: json["invoice_started"],
  //       dailyReset: json["daily_reset"],
  //       otp: json["otp"],
  //       xid: json["xid"],
  //       logoUrl: json["logo_url"],
  //       darkLogoUrl: json["dark_logo_url"],
  //       signatureUrl: json["signature_url"],
  //     );
  //
  // Map<String, dynamic> toJson() => {
  //       "company_id": companyId,
  //       "logo": logo,
  //       "dark_logo": darkLogo,
  //       "name": name,
  //       "slug": slug,
  //       "email": email,
  //       "phone": phone,
  //       "show_email_on_invoice": showEmailOnInvoice,
  //       "show_phone_on_invoice": showPhoneOnInvoice,
  //       "address": address,
  //       "terms_condition": termsCondition,
  //       "bank_details": bankDetails,
  //       "signature": signature,
  //       "gst_in_no": gstInNo,
  //       "qr_code": qrCode,
  //       "upi_id": upiId,
  //       "online_store_enabled": onlineStoreEnabled,
  //       "customers_visibility": customersVisibility,
  //       "suppliers_visibility": suppliersVisibility,
  //       "products_visibility": productsVisibility,
  //       "default_pos_order_status": defaultPosOrderStatus,
  //       "show_mrp_on_invoice": showMrpOnInvoice,
  //       "show_discount_tax_on_invoice": showDiscountTaxOnInvoice,
  //       "created_at": createdAt.toIso8601String(),
  //       "updated_at": updatedAt.toIso8601String(),
  //       "pos_type": posType,
  //       "set_pos_type": setPosType,
  //       "is_barcode": isBarcode,
  //       "is_wainvoice": isWainvoice,
  //       "first_invoice_no": firstInvoiceNo,
  //       "prefix_invoice": prefixInvoice,
  //       "invoice_spliter": invoiceSpliter,
  //       "suffix_invoice": suffixInvoice,
  //       "reset_invoice": resetInvoice,
  //       "invoice_started": invoiceStarted,
  //       "daily_reset": dailyReset,
  //       "otp": otp,
  //       "xid": xid,
  //       "logo_url": logoUrl,
  //       "dark_logo_url": darkLogoUrl,
  //       "signature_url": signatureUrl,
  //     };
}
